### ISSUE TITLE
Please add 'Hacktober-Accepted'

### ISSUE THREAD

**Issue by Rishit30G** [viveakrt/Competitive-programing-hacktoberfest-2021#134]
![image](https://user-images.githubusercontent.com/74411873/135648431-b593cf77-10bd-4001-b988-e4c17d8241ab.png)

You have merged my file but forgot to add 'Hacktober-Accepted' on it

**Comment by viveakrt** [comment]
I will add , but it doesn't matter if you PR is merged, repo already have hacktober tag
